server:
  port: 8802

spring:
  ##邮箱发送配置
  ##连接池配置
  datasource:
    druid:
      driverClassName: oracle.jdbc.OracleDriver
      # allowMultiQueries=true 支持一次执行多条 sql
      url: jdbc:oracle:thin:@192.168.100.104:1521:ORCL
      username: YEIG_AUDIT
      password: ei123456
      initialSize: 5
      minIdle: 5
      maxActive: 20
      ##连接等待超时时间
      maxWait: 60000
      ##配置隔多久进行一次检测(检测可以关闭的空闲连接)
      timeBetweenEvictionRunsMillis: 60000
      ##配置连接在池中的最小生存时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT '1' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      ## 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      ## 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，加上 wall 无法一次执行多条 sql，所以去掉
      filters: stat,slf4j
      ## 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  # mybatis 的 mapper 文件扫描路径
  mapperLocations:
    - classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    useColumnLabel: true
  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: shuqikeji@qq.com
    password: trhbxmkgtpqzcjfa
    properties.mail.smtp.auth: true
    #      properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: aaa #可以任意
    properties.mail.display.sendname: bbb #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#邮箱格式
title:
  【数起科技有限公司邮箱验证服务】